name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check code format with black
      run: |
        pip install black
        black --check pert
        black --check tests
    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest
